/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import control.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SMKN1Rembang-PC
 */
public class cetak extends javax.swing.JFrame {

    /**
     * Creates new form cetak
     */
    public cetak() {
        initComponents();
        printdata.setEditable(false);
        biayaantar.setEditable(false);
        biayahari.setEditable(false);
        biayajemput.setEditable(false);
        biayalayanan.setEditable(false);
        total.setEditable(false);
        kembalian.setEditable(false);
        item.setEditable(false);
    }
    
    
    public void tampilCetak(String kode){
        try {
            ResultSet rs = koneksi.getConnection().createStatement().executeQuery("SELECT pesan.kode_order,pesan.kode_pelanggan,nama,pesan.no_telepon,alamat,jenis_layanan,biaya,jumlah_unit,tanggal_order,tanggal_selesai,biaya_antar,biaya_jemput,biaya_hari,petugas_antar,status_order FROM pelanggan INNER JOIN pesan ON pesan.kode_pelanggan = pelanggan.kode_pelanggan INNER JOIN detail_order ON pesan.kode_order = detail_order.kode_order WHERE pesan.kode_order like '%"+kode+"%'");
            while(rs.next()){
                printdata.setText("==============================================\n");
                printdata.setText(printdata.getText()+"\t Laundry Express \n");
                printdata.setText(printdata.getText()+"Nama \t : "+rs.getString(3)+"\n");
                printdata.setText(printdata.getText()+"Telepon \t : "+rs.getString(4)+"\n");
                printdata.setText(printdata.getText()+"Alamat \t : "+rs.getString(5)+"\n");
                printdata.setText(printdata.getText()+"Jenis Layanan \t : "+rs.getString(6)+"\n");
                printdata.setText(printdata.getText()+"==============================================\n");
                biayalayanan.setText(rs.getString(7));
                item.setText(rs.getString(8));
                biayaantar.setText(rs.getString(11));
                biayajemput.setText(rs.getString(12));
                biayahari.setText(rs.getString(13));
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printdata = new javax.swing.JTextArea();
        biayaantar = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        biayalayanan = new javax.swing.JTextField();
        biayahari = new javax.swing.JTextField();
        biayajemput = new javax.swing.JTextField();
        item = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(100, 100, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cetak");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 717, -1));

        printdata.setColumns(20);
        printdata.setRows(5);
        jScrollPane1.setViewportView(printdata);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 103, 342, 322));
        jPanel1.add(biayaantar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, 110, 28));

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 517, 101, 43));

        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });
        jPanel1.add(Cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 517, 104, 43));
        jPanel1.add(biayalayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 210, 117, 28));
        jPanel1.add(biayahari, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 210, 107, 28));
        jPanel1.add(biayajemput, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 147, 117, 28));
        jPanel1.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 271, 107, 28));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 302, 107, 28));
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 368, 107, 28));
        jPanel1.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 427, 107, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kembalian");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bayar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Biaya Antar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Biaya Jemput");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Biaya Hari");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Biaya Layanan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        
        int tbiayaantar,tbiayahari,tbiayalayanan,tbiayajemput,titem,hasil;
            tbiayaantar = Integer.valueOf(biayaantar.getText());
            tbiayahari = Integer.valueOf(biayahari.getText());
            tbiayalayanan = Integer.valueOf(biayalayanan.getText());
            tbiayajemput = Integer.valueOf(biayajemput.getText());
            titem = Integer.valueOf(item.getText());

            if(Hitung.getText().equals("Hitung")){
                hasil = (tbiayaantar + tbiayajemput + tbiayahari +(tbiayalayanan * titem));
                total.setText(String.valueOf(hasil));
                printdata.setText(printdata.getText()+"Biaya Antar \t : "+biayaantar.getText()+"\n");
                printdata.setText(printdata.getText()+"Biaya Jemput \t : "+biayajemput.getText()+"\n");
                printdata.setText(printdata.getText()+"Biaya Hari \t : "+biayahari.getText()+"\n");
                printdata.setText(printdata.getText()+"Biaya Layanan \t : "+biayalayanan.getText()+"\n");
                printdata.setText(printdata.getText()+"Biaya Item \t : "+item.getText()+"\n");
                printdata.setText(printdata.getText()+"==============================================\n");
                Hitung.setText("Bayar");
            }else if(Hitung.getText().equals("Bayar")){
                if(bayar.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
                }else{
                    int subtotal, bayaran,kembali;
                    subtotal = Integer.valueOf(total.getText());
                    bayaran = Integer.valueOf(bayar.getText());
                    kembali = bayaran - subtotal;
                    kembalian.setText(String.valueOf(kembali));
                    Hitung.setText("Selesai");
                }
            }else if(Hitung.getText().equals("Selesai")){
                printdata.setText(printdata.getText()+"Bayar \t : "+bayar.getText()+"\n");
                printdata.setText(printdata.getText()+"Total \t : "+total.getText()+"\n");
                printdata.setText(printdata.getText()+"Kembalian \t : "+kembalian.getText()+"\n");
                Hitung.setText("Hitung");
                reset();
            }
        
    }//GEN-LAST:event_HitungActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        try {
            printdata.print();
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_CetakActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked
    
    private void reset(){
        biayaantar.setText("");
        biayalayanan.setText("");
        biayajemput.setText("");
        biayahari.setText("");
        item.setText("");
        total.setText("");
        bayar.setText("");
        kembalian.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cetak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField biayaantar;
    private javax.swing.JTextField biayahari;
    private javax.swing.JTextField biayajemput;
    private javax.swing.JTextField biayalayanan;
    private javax.swing.JTextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextArea printdata;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
