/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import control.control_orderan;
import control.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Oki Ardana
 */
public class editorder extends javax.swing.JFrame {

    /**
     * Creates new form editorder
     */
    control_orderan control_orderan;
    
    public editorder() {
        initComponents();
        kodeorder.setVisible(false);
        kodepelanggan.setVisible(false);
        control_orderan = new control_orderan();
        control_orderan.pilihCombo(layanan,"SELECT jenis_layanan FROM layanan");
        control_orderan.pilihCombo(biayahari,"SELECT biaya FROM biaya_tambahan");
        control_orderan.pilihCombo(petugas,"SELECT nama_petugas FROM petugas_antar");
       
    }
    
    public void tampilEdit(String kode){
        try {
            ResultSet rs = koneksi.getConnection().createStatement().executeQuery("SELECT pesan.kode_order,pesan.kode_pelanggan,nama,pesan.no_telepon,alamat,jenis_layanan,biaya,jumlah_unit,tanggal_order,tanggal_selesai,biaya_antar,biaya_jemput,biaya_hari,petugas_antar,status_order FROM pelanggan INNER JOIN pesan ON pesan.kode_pelanggan = pelanggan.kode_pelanggan INNER JOIN detail_order ON pesan.kode_order = detail_order.kode_order WHERE pesan.kode_order like '%"+kode+"%'");
            while(rs.next()){
                kodeorder.setText(rs.getString(1));
                kodepelanggan.setText(rs.getString(2));
                nama.setText(rs.getString(3));
                telepon.setText(rs.getString(4));
                alamat.setText(rs.getString(5));
                layanan.setSelectedItem(rs.getString(6));
                biayalayanan.setText(rs.getString(7));
                item.setText(rs.getString(8));
                biayaantar.setText(rs.getString(11));
                biayajemput.setText(rs.getString(12));
                biayahari.setSelectedItem(rs.getString(13));
                petugas.setSelectedItem(rs.getString(14));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        item = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodeorder = new javax.swing.JTextField();
        kodepelanggan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kodeorder1 = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        ubahorderan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        biayaantar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        biayalayanan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        biayajemput = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(100, 100, 255));
        jPanel1.setForeground(new java.awt.Color(249, 241, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 135, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Telepon");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Edit Data Order");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 770, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 40, 30));

        kodeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeorderActionPerformed(evt);
            }
        });
        jPanel2.add(kodeorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 135, 35));

        kodepelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodepelangganActionPerformed(evt);
            }
        });
        jPanel2.add(kodepelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 135, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 768, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Biaya antar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        kodeorder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeorder1ActionPerformed(evt);
            }
        });
        jPanel1.add(kodeorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 135, 35));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 135, 35));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, -1));

        ubahorderan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ubahorderan.setText("Edit");
        ubahorderan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahorderanActionPerformed(evt);
            }
        });
        ubahorderan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ubahorderanKeyPressed(evt);
            }
        });
        jPanel1.add(ubahorderan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 140, 50));

        biayahari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        jPanel1.add(biayahari, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 130, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 135, 34));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Layanan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        jPanel1.add(biayaantar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 135, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Biaya");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Item");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));
        jPanel1.add(biayalayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 135, 34));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Biaya jemput");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));
        jPanel1.add(biayajemput, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 135, 34));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Biaya hari");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        layanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih" }));
        jPanel1.add(layanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 130, 40));

        petugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih" }));
        jPanel1.add(petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 130, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Petugas antar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kodeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeorderActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void kodepelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodepelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodepelangganActionPerformed

    private void kodeorder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeorder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeorder1ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void ubahorderanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahorderanActionPerformed
        if(kodeorder.getText().isEmpty() || kodepelanggan.getText().isEmpty() || nama.getText().isEmpty() || telepon.getText().isEmpty() || alamat.getText().isEmpty() || layanan.getSelectedItem().equals("pilih") || biayalayanan.getText().isEmpty() || item.getText().isEmpty() || biayahari.getSelectedItem().equals(0)){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
        }else if(telepon.getText().length() != 12){
            JOptionPane.showMessageDialog(null, "No Telepon Harus 12 Digit");
        }else{
            control_orderan.editOrder(kodeorder, kodepelanggan, nama, telepon, alamat, layanan, biayalayanan, item, biayaantar, biayajemput, biayahari, petugas);
            dispose();
            reset();
            control_orderan.refreshOrderan(admin.tabelorderan);
        }
    }//GEN-LAST:event_ubahorderanActionPerformed

    private void ubahorderanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubahorderanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahorderanKeyPressed
     
        private void reset(){
            nama.setText("");
            telepon.setText("");
            alamat.setText("");
            layanan.setSelectedItem("pilih");
            biayalayanan.setText("");
            item.setText("0");
            biayahari.setSelectedItem("0");
            biayaantar.setText("0");
            biayajemput.setText("0");
            petugas.setSelectedItem("pilih");
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField biayaantar;
    public static final javax.swing.JComboBox<String> biayahari = new javax.swing.JComboBox<>();
    private javax.swing.JTextField biayajemput;
    private javax.swing.JTextField biayalayanan;
    private javax.swing.JTextField item;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodeorder;
    private javax.swing.JTextField kodeorder1;
    private javax.swing.JTextField kodepelanggan;
    public static final javax.swing.JComboBox<String> layanan = new javax.swing.JComboBox<>();
    private javax.swing.JTextField nama;
    public static final javax.swing.JComboBox<String> petugas = new javax.swing.JComboBox<>();
    private javax.swing.JTextField telepon;
    private javax.swing.JButton ubahorderan;
    // End of variables declaration//GEN-END:variables
}
